### ISSUE TITLE
Customizable notifications

### ISSUE THREAD

**Issue by tadly** [linuxwhatelse/dups#9]
Would be nice to configure exactly what notifications are posted.
Thinking of something like:
```yaml
notify:
  backup:
    start: True
    finish: True
    error: True
  restore:
    start: True
    finish: True
    error: True
```

Just a quick draft though so I don't forget again

**Comment by tadly** [comment]
Or have the config in an `enum` kinda style like:
```yaml
# Possible options are: NONE, ALL, FINISH, ERROR
#   NONE: Don't post any notifications
#   ALL: Post all notifications
#   DONE: Only post notifications when the process finished successfully or with errors
#   ERROR: Only post notifications when the process finished with errors
notify:
  backup: ALL
  restore: ALL
```

**Comment by tadly** [comment]
Ooooooor we use the notification priority maybe?
Or have the config in an `enum` kinda style like:
```yaml
# Possible options are: NONE, LOW, NORMAL, HIGH, URGENT
#   NONE: Don't post any notifications
#   LOW: Post all notifications
#   NORMAL: Post all notifications excluding LOW
#                      Includes start notifications
#   HIGH: Post all notifications excluding LOW and NORMAL
#               Includes warnings about incomplete backups/restores
#   URGENT: Post all notifications excluding LOW, NORMAL and HIGH
#                      Includes warnings about failed backups/restores
notify:
  backup: NORMAL
  restore: NORMAL
```

I think I like this best right now as it would allow to go nuts with notifications (using `LOW`) in the future.
No idea what additional notifications we could post but hey `¯\_(ツ)_/¯`

p.s. The outlined use of `HIGH` and `URGENT` is not yet implemented the way I described it in the comment above but certainly should be.
